# Generated by Django 3.0.3 on 2020-02-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OK',
        ),
    ]
